#!/bin/bash

name_dir="$1 at $(date)"
mkdir "$name_dir"
cd "$name_dir"

mkdir about_me
mkdir about_me/personal
echo "https://www.facebook.com/$2" > about_me/personal/facebook.txt

mkdir about_me/professional
echo "https://www.linkedin.com/in/$3" > about_me/professional/linkedin.txt

mkdir my_system_info
echo "My username: $USER" > my_system_info/about_this_laptop.txt
echo "With host: $(uname -a)" >> my_system_info/about_this_laptop.txt

echo "Connection to google:" > my_system_info/internet_connection.txt
echo "$(ping forcesafesearch.google.com -c 3)" >> my_system_info/internet_connection.txt

mkdir my_friends
echo "1) Achmad Miftahul - amulum" > my_friends/list_of_my_friends.txt
echo "2) Achmad Rafiq - achmadrafiq97" >> my_friends/list_of_my_friends.txt
echo "3) Adiststi - adiststi" >> my_friends/list_of_my_friends.txt
echo "4) Agung - agungajin19" >> my_friends/list_of_my_friends.txt
echo "5) Azzahra - al7262" >> my_friends/list_of_my_friends.txt
echo "6) Charisma - fadzrichar" >> my_friends/list_of_my_friends.txt
echo "7) Farida - ulfarida" >> my_friends/list_of_my_friends.txt
echo "8) Garry - garryarielcussoy" >> my_friends/list_of_my_friends.txt
echo "9) Hamdi - hamdiranu" >> my_friends/list_of_my_friends.txt
echo "10) Hedy Gading - Gading09" >> my_friends/list_of_my_friends.txt
echo "11) Ilham - aamfatur" >> my_friends/list_of_my_friends.txt
echo "12) Lelianto - Lelianto">>  my_friends/list_of_my_friends.txt
echo "13) Mohammad - daffa99" >> my_friends/list_of_my_friends.txt
echo "14) Muhammad Fadhil - fabdulkarim" >> my_friends/list_of_my_friends.txt
echo "15) Ofbimon - bimon-alta" >> my_friends/list_of_my_friends.txt
echo "16) Purnama Syafitri - pipitmnr" >> my_friends/list_of_my_friends.txt
echo "17) Setyo - setyoyo07" >> my_friends/list_of_my_friends.txt
echo "18) Wildan - wiflash" >> my_friends/list_of_my_friends.txt
echo "19) Willy - sumarnowilly94" >> my_friends/list_of_my_friends.txt
echo "20) Woka - woka20" >> my_friends/list_of_my_friends.txt